package com.kanban.notification.domain;

public enum NotificationType {
    CARD_ASSIGNMENT, CARD_MENTION, COMMENT_MENTION, SYSTEM, CARD_WATCH, DUE_DATE_IMMINENT, BOARD_INVITATION, INVITATION_CANCELLED
}
