-- 활동 로그 event_type 체크 제약 재정의 (새 이벤트 추가: CARD_STARTED, CARD_COMPLETED, CARD_REOPENED)
-- 기존 자동 생성 제약(CONSTRAINT_9 등)을 제거 후 새로운 체크 제약을 추가합니다.

-- 기존 제약 제거 (자동 생성 이름을 방어적으로 모두 시도)
ALTER TABLE activities DROP CONSTRAINT IF EXISTS CONSTRAINT_9;
ALTER TABLE activities DROP CONSTRAINT IF EXISTS CONSTRAINT_8;
ALTER TABLE activities DROP CONSTRAINT IF EXISTS CK_ACTIVITIES_EVENT_TYPE;

-- 새 체크 제약 추가
ALTER TABLE activities
    ADD CONSTRAINT CK_ACTIVITIES_EVENT_TYPE CHECK (
        event_type IN (
            'BOARD_CREATED', 'BOARD_UPDATED', 'BOARD_DELETED',
            'COLUMN_CREATED', 'COLUMN_UPDATED', 'COLUMN_DELETED', 'COLUMN_REORDERED',
            'CARD_CREATED', 'CARD_UPDATED', 'CARD_DELETED', 'CARD_MOVED',
            'CARD_STARTED', 'CARD_COMPLETED', 'CARD_REOPENED',
            'MEMBER_INVITED', 'MEMBER_ROLE_CHANGED', 'MEMBER_REMOVED',
            'COMMENT_ADDED', 'COMMENT_DELETED'
        )
    );
